### ISSUE TITLE
session recognition..

### ISSUE THREAD

**Issue by samberkni** [jofpin/trape#102]
session recognition

**Comment by samberkni** [comment]
@dinopio how ...

**Comment by jofpin** [comment]
Must be some incompatibility with the browser. I'll check, though if you can check it would be great.

**Comment by samberkni** [comment]
> 
> 
> They do not work the recognition of sessions?


i tried mozila and chrome and edge all without success

**Comment by samberkni** [comment]
@jofpin  any luck ....

**Comment by DJCHICKEN4** [comment]
I also have this issue I originally tried using Linux subsystems on windows then after experiencing this changed to a kali linux VM to no avail.

**Comment by DJCHICKEN4** [comment]
> Must be some incompatibility with the browser. I'll check, though if you can check it would be great.

I have tested the hook link on Microsoft Edge, Chrome and Firefox on a PC (In both incognito mode to avoid interference of extensions and regular browsing). Silk browser on a Kindle Fire and Safari on an iPhone I don't believe that it is a browser incompatibility issue.

**Comment by M2z** [comment]
Same issue over here

**Comment by DJCHICKEN4** [comment]
I’ll see if I can find the issue and work on a patch when I have the time.

**Comment by samberkni** [comment]
ok please try soon .

**Comment by DJCHICKEN4** [comment]
Sadly I cannot find where the issue stems from and I even tried a couple of older versions of trape and came out empty handed.

**Comment by samberkni** [comment]
@jofpin  have you found the problem here because everyone seems to have the same issue.

**Comment by DJCHICKEN4** [comment]
Just a quick update: I have found the issue (and hopefully solution) and I am working on a patch. Expect it in about 1-3 days.

**Comment by samberkni** [comment]
> 
> 
> Just a quick update: I have found the issue (and hopefully solution) and I am working on a patch. Expect it in about 1-3 days.

awesome waiting for your solution.

**Comment by halisi** [comment]
Great

**Comment by DJCHICKEN4** [comment]
@samberkni I have confirmed my solution works however only on the local computer. Right now I’m working on using ngrok to fix that.

**Comment by DJCHICKEN4** [comment]
@samberkni I haven’t test that yet but will make an update post later today.

**Comment by DJCHICKEN4** [comment]
@samberkni  #115 This should work for a fix to the issue until I release a patch that allows the service to be run on the local computer so that this issue won't occur again.

**Comment by jofpin** [comment]
Hello hackers, the problem has already been solved by a community user.

https://github.com/jofpin/trape/pull/115

@DJCHICKEN4 thanks!
