### ISSUE TITLE
wrong url in dashboard + js

### ISSUE THREAD

**Issue by roobandev** [jofpin/trape#103]
Command i used to run
python trape.py --url https://www.google.com --port 8080

1. JS has double http in the .js rest api path

(function() { var paths = [ '**http://http://**xxxx.ngrok.io/static/js/xxx', '**http://http**://xxxx.ngrok.io/static/js/xxx', '**http://http://**xxxx.ngrok.io/static/js/xxxx' ]; window.gMapsApiKey = "xxxxxxxxxxxxxxxxxxxxxx"; var imported = {}; var idx = 0; loadScript(function(){ idx++; loadScript(function(){ idx++; window.serverPath = '**http://http**://xxxxx.ngrok.io'; loadScript(function(){ idx++; }); }); }); function loadScript(callback){ imported = document.createElement('script'); imported.type = 'text/javascript'; imported.src = paths[idx]; imported.onload = callback; var head = document.getElementsByTagName('head')[0]; head.appendChild(imported, head); } }())

2. In the dashboard page, there is also error in the url
![screenshot from 2018-11-28 22-19-23](https://user-images.githubusercontent.com/11260305/49167800-2a7a5080-f35c-11e8-9c1b-4a96aea56b63.png)

**Comment by DJCHICKEN4** [comment]
Remove the https://www. from the command so it would be
`python trape.py --url google.com --port 8080`

**Comment by DJCHICKEN4** [comment]
@roobandev What OS are you using?

**Comment by roobandev** [comment]
@DJCHICKEN4 Ubuntu 18.04 x64

**Comment by DJCHICKEN4** [comment]
Is it being run in a Virtual Machine or Booted from USB or Run from hard drive?

**Comment by roobandev** [comment]
running it in a vultr instance

**Comment by DJCHICKEN4** [comment]
try running the command
`python trape.py`
Then enter the URL and port manually.

**Comment by roobandev** [comment]
Still not working

**Comment by DJCHICKEN4** [comment]
Try using Kali Linux (either through USB or VM) and/or uninstalling and reinstalling trape.

**Comment by roobandev** [comment]
I will try with other Linux version and update

**Comment by roobandev** [comment]
@DJCHICKEN4  looks to be no issues with distro.

changed code from core/stats.py (line 75)

```
if trape.nGrokUrl != '':
injectCode = 'http://' + str(trape.nGrokUrl) + '/' + str(trape.injectURL)
```

to

```
if trape.nGrokUrl != '':
        server_code = str(trape.nGrokUrl)

```
It is just a hard code fix (because i don't know python). It partially works now

**Comment by DJCHICKEN4** [comment]
I see, what do you mean by it partially works?

**Comment by roobandev** [comment]
I meant it solved my problem no. 1 :)

**Comment by DJCHICKEN4** [comment]
Try changing the code in core/stats.py (line 75) to this 
`if trape.nGrokUrl != '':
injectCode = str(trape.nGrokUrl) + '/' + str(trape.injectURL)`
because the html relies on the injectCode variable for displaying the link

**Comment by DJCHICKEN4** [comment]
I am working on a patch and will let you know when I'm done.

**Comment by DJCHICKEN4** [comment]
I'll be working on patch and keep you updated.

**Comment by DJCHICKEN4** [comment]
Done https://github.com/jofpin/trape/pull/104
