### ISSUE TITLE
Cannot see any of the credentials or cookies

### ISSUE THREAD

**Issue by Sara123984** [jofpin/trape#109]
I have successfully installed and configured this tool using Kali VM, it works sometimes.
But I cannot see any user credentials or cookies from his tab or apps, am I missing something, or I do have to run some other payload in order to do that ?

All the amazon, google, fb, tw and so on sessions seem off, even if they are opened, in that browser and also in the app.

Can someone tell me what to do ?

**Comment by samberkni** [comment]
same issue here it seems it doesn't work for anyone

**Comment by pdelteil** [comment]
I tried to log in on the lure url (fckb, gmail) and I couldn't from Android. Then I managed to login using Chrome on a Desktop computer but nothing happened.

**Comment by jofpin** [comment]
Hello hackers, the problem has already been solved by a community user.

https://github.com/jofpin/trape/pull/115

@DJCHICKEN4 thanks!
