### ISSUE TITLE
General Config - Ngrok Token & Google Api Key LOOPING !

### ISSUE THREAD

**Issue by anonsec007** [jofpin/trape#124]
Ngrok Token - Given
Google Api Key - Given

But Again And Again It's Showing The Same Option !

**Comment by Soutcast** [comment]
I get the same issue. Do you know how to fix?

**Comment by DJCHICKEN4** [comment]
@Soutcast Could you check the config file (trape.config) and tell me if your keys are displayed in the proper sections if not try entering the key into the file.

**Comment by Soutcast** [comment]
@DJCHICKEN4 I entered the Ngrok token and the gmaps api key into the `trape.py` file located in the core folder and the same issues still occurs

**Comment by aeroxy** [comment]
@TheMasterOfE no trape.config file is found under the project folder...

**Comment by theonlycolm** [comment]
This is still happening - what was the solution?
