### ISSUE TITLE
Doesn't show links

### ISSUE THREAD

**Issue by Parshuram2** [jofpin/trape#138]
the command "python2 trape.py -u https://www.facebook.com -p 8080"
 just shows
 loading trape and says
 "get lucky on the way"..That is it.
cannot see the links. I have ngrok token and google maps API as well.
 I go to 127.0.0.1/site...it doesn't connect. what am I missing?

**Comment by ImBIOS** [comment]
It happens to me too. How you @Parshuram2 solve this issue?
