### ISSUE TITLE
CSS is not being loaded in control panel

### ISSUE THREAD

**Issue by GorkaAbad** [jofpin/trape#143]
Hey,
CSS is no being loaded while in control panel. Im wondering if the CSS path is not correct, since i dont have any "styles" folder, which is the one is searching for.
Thanks in advance

**Comment by DJCHICKEN4** [comment]
@GorkaAbad I'll take a look at this issue.

**Comment by GorkaAbad** [comment]
Okay thanks a lot

**Comment by DJCHICKEN4** [comment]
@GorkaAbad Could you send me a screenshot.

**Comment by GorkaAbad** [comment]
![Captura de pantalla de 2019-03-21 15-34-33](https://user-images.githubusercontent.com/25768826/54759838-29ad4900-4bef-11e9-9706-5cac966ee487.png)
![Captura de pantalla de 2019-03-21 15-37-28](https://user-images.githubusercontent.com/25768826/54759965-68430380-4bef-11e9-9d32-38490d5ad662.png)

@DJCHICKEN4 Same happens after inserting the access key.

**Comment by CroixA** [comment]
Hi,

I have the same issue :/. Have you find a solution to solve this problem ?

Thanks for your answer

**Comment by GorkaAbad** [comment]
Hi,
No I don't sorry. I tried it out in another computer and it worked. 
But I havn't come up with any solution yet.
Ill let you know if I find something

**Comment by DJCHICKEN4** [comment]
Have you tried using a different browser or incognito mode?

**Comment by GorkaAbad** [comment]
Yes, I did, and same happened

**Comment by CroixA** [comment]
I just tried with two different browsers in normal mode and incognito mode. And on another computer. That's not working.

**Comment by pobreiluso** [comment]
I experienced the same issue, but adding a initial slash to all the css files in the variable CSSFiles of trape.py solved the issue for me.

`diff --git a/core/trape.py b/core/trape.py
index 9ab8dc3..d05f51c 100755
--- a/core/trape.py
+++ b/core/trape.py
@@ -43,7 +43,7 @@ class Trape(object):
                self.nGrokUrl = ''
 
                self.JSFiles = ({"path" : "base.js", "src" : utils.generateToken(12)},{"path" : "libs.min.js", "src" : utils.generateToken(12)},{"path" : "login.js", "src" : utils.generateToken(12)},{"path" : "payload.js", "src" : utils.generateToken(12)},{"path" : "trape.js", "src" : utils.generateToken(12)},{"path" : "vscript.js", "src" : utils.generateToken(12)},)
-               self.CSSFiles = ({"path" : "static/img/favicon.ico", "src" : utils.generateToken(12)},{"path" : "static/img/favicon.png", "src" : utils.generateToken(12)},{"path" : "static/css/base-icons.css", "src" : utils.generateToken(12)},{"path" : "static/css/styles.css", "src" : utils.generateToken(12)},{"path" : "static/css/normalize.min.css", "src" : utils.generateToken(12)},{"path": "static/css/services-icons.css", "src" : utils.generateToken(12)},)
+               self.CSSFiles = ({"path" : "/static/img/favicon.ico", "src" : utils.generateToken(12)},{"path" : "/static/img/favicon.png", "src" : utils.generateToken(12)},{"path" : "/static/css/base-icons.css", "src" : utils.generateToken(12)},{"path" : "/static/css/styles.css", "src" : utils.generateToken(12)},{"path" : "/static/css/normalize.min.css", "src" : utils.generateToken(12)},{"path": "/static/css/services-icons.css", "src" : utils.generateToken(12)},)
 
                if self.stat == 1:
                        c = httplib.HTTPConnection('www.google.com', timeout=5)
`

**Comment by CroixA** [comment]
That's working ! Thank you very much !

**Comment by GorkaAbad** [comment]
Yes same to me.
It is working now.
Thanks @pobreiluso
