### ISSUE TITLE
Protocol not available? 

### ISSUE THREAD

**Issue by CrossBrain** [jofpin/trape#16]
![image](https://user-images.githubusercontent.com/33381728/32694918-1f813eaa-c71b-11e7-9c03-fa1d722036b5.png)

**Comment by jofpin** [comment]
Are you sure you installed all the indicated libraries?

**Comment by CrossBrain** [comment]
Yes

**Comment by ubaidsworld** [comment]
@CrossBrain  This may be because you have used the site as Google.com. Try using another site I guess it will work. Google might have certain restrictions.

**Comment by st4nn** [comment]
Hi @CrossBrain, can you paste the line that you are using for run trape please?

**Comment by jofpin** [comment]
Hey! Enjoy the new version 2.0 stable, brings many features included and correcting bugs. 

https://github.com/jofpin/trape

Share the World and Happy hacking!
