### ISSUE TITLE
URL Shortener, Maps API Error

### ISSUE THREAD

**Issue by gobinathan-l** [jofpin/trape#167]
when i run trape it shows up goo,gl forbidden instead of showing shortened url. Can some one help me with fixing this issue . Tutorial on Creating a perfect api key for url shortener would be welcome.
On trape control panel the Maps says it couldn't show the location of this user.

**Comment by orestescaminha** [comment]
The URL Shortener API was deprecated. https://developers.google.com/apps-script/advanced/url-shortener?hl=pt-br
