### ISSUE TITLE
Installation ERROR

### ISSUE THREAD

**Issue by Cipher-Aryan** [jofpin/trape#199]
Hello 
I'm having some trouble while installing trape (requirements have been installed)
Traceback (most recent call last):
  File "trape.py", line 23, in <module>
    from core.utils import utils                  #
  File "/home/aryan/Desktop/trape/core/utils.py", line 23, in <module>
    import http.client
ImportError: No module named http.client

**Comment by ronnytittoto** [comment]
> 
> 
> Hello
> I'm having some trouble while installing trape (requirements have been installed)
> Traceback (most recent call last):
> File "trape.py", line 23, in
> from core.utils import utils #
> File "/home/aryan/Desktop/trape/core/utils.py", line 23, in
> import http.client
> ImportError: No module named http.client

same issue here on a debian 10.2

**Comment by harshitm98** [comment]
Replacing everywhere `http.client` with `httplib` in trape/core/utils.py file worked for me.

The reason is because `httplib` is renamed to `http.client` for Python3. [Link to httplib documentation](https://docs.python.org/2/library/httplib.html)

**Comment by Cipher-Aryan** [comment]
Thanks that solved my issue @harshitm98

**Comment by tonovicio** [comment]
eu fiz a mudança mas não pegou
