### ISSUE TITLE
Unable to create new account at ipgeolocation.io

### ISSUE THREAD

**Issue by syarz** [jofpin/trape#241]
Hi, I have used trape and it was pretty straight a while ago but now since you have made some changes to it, it has become more complicated to run the script for newbies. Although the problem which I'm having may not seems related to trape, since it asks users to register with ipgeolocation.io and insert API key but when you land on the sign-up page on the site, the captcha keeps coming and won't let me sign-up. Any help would be appreciated. Thank you

**Comment by djhashh** [comment]
worked fine for me, took like 2 seconds..

**Comment by syarz** [comment]
@djhashh thanks for the quick response. I haven't tried since then, will give it one more shot, let's see if it works
