### ISSUE TITLE
when I execute,it is showing this error : [Error 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Ajay-creator** [jofpin/trape#252]
ERROR: [Error 2] The system cannot find the file specified

**Comment by Ajay-creator** [comment]
ERROR: [Error 2] The system cannot find the file specified

**Comment by puthusseri** [comment]
> ERROR: [Error 2] The system cannot find the file specified

Show the complete error. Including the line number.

**Comment by Ajay-creator** [comment]
I have given the info of all the required tokens, URL and port
After that, I got the following error.

<img width="467" alt="Annotation 2020-08-06 164002" src="https://user-images.githubusercontent.com/54075270/89525643-21fe3c80-d804-11ea-9788-8dcf9e1855e6.png">

**Comment by gxlsilverrr6** [comment]
Im getting the same error also

**Comment by OdincoGaming** [comment]
download ngrok and extract it to trape folder

**Comment by OdincoGaming** [comment]
> 
> 
> I'm receiving the same error.



> 
> 
> Im getting the same error also
