### ISSUE TITLE
[x] ERROR: cannot import name JSONDecodeError

### ISSUE THREAD

**Issue by DSRobin** [jofpin/trape#277]
Hii,

I'm encountering this error when running trape in Python 2.7.16+ on Kali Linux "2020.2 Kali-Rolling"
I've installed all the requirements, tho.

**Comment by piyushverma001** [comment]
Yes Even I have this issue on both ubuntu and windows machines with python 2.7.18 installed.
The root of the issue is with `flask_socketio` module which fails import in python2.7 due to this JSONDecodeError.

**Comment by DSRobin** [comment]
So, is there any solution to this?

Sent from my Nokia 3310


-------- Original message --------

**Comment by piyushverma001** [comment]
ig `json` raises a `ValueError` instead of `JSONDecodeError` (as raised by `simplejson`) which is a sub class of `ValueError`. And the problem is with the `flask_socketio` module and not trape, which needs a fix. Till then as I mentioned, the temporary solution works perfetly fine for me.

**Comment by DSRobin** [comment]
I didn't see your temporary fix at first. I got it up and running on windows, thanks to your fix. However on Kali I was unable to locate the engineio/client.py file.

Sent from my Nokia 3310


-------- Original message --------

**Comment by BlackGoku724** [comment]
> Sí, incluso tengo este problema en máquinas ubuntu y windows con python 2.7.18 instalado.
> La raíz del problema es con el `flask_socketio`módulo que falla la importación en python2.7 debido a este JSONDecodeError.
> 
> Y la solución temporal a este problema para ejecutar `pip install simplejson`e ir al `C:\....\python27\Lib\site-packages\engineio\client.py`archivo y cambiar `from json import JSONDecodeError`a `from simplejson import JSONDecodeError`. Esto me lo resuelve.

Your route is wrong because what you say does not appear to me. After Going python2.7, the other folders that you indicate do not appear.

**Comment by Boba2601** [comment]
It's bad route
1.pip install simplejson
2. python2
3. from simplejson import JSONDecodeError
But he still doesn't see it, at least for me.

**Comment by BlackGoku724** [comment]
> It's bad route
> 1.pip2 install simplejson (pip install python 3)
> 2. python2
> 3. from simplejson import JSONDecodeError
> But he still doesn't see it, at least for me.

I keep throwing the same error.

**Comment by depsiFi** [comment]
Worked for me. At first It didn't because I changed the python3 client.py, but then I found the 2.7 version and it fixed it. Thanks)

**Comment by lucilu1320** [comment]
hey @depsiFi go for this:
pip install "Flask-SocketIO<5.0.0"
Hope so this fixes!

**Comment by NLPoker** [comment]
Anyone know where to find the 2.7 client.py on Mac OSX?

**Comment by lucilu1320** [comment]
hey @NLPoker  you can find it here i guess so:
 /opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/client.py
or
/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/dist-packages/client.py

**Comment by NLPoker** [comment]
> hey @NLPoker you can find it here i guess so:
> /opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/client.py
> or
> /opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/dist-packages/client.py

I don't have either dist-packages or site-packages in any of my python folders

**Comment by NLPoker** [comment]
> > hey @NLPoker you can find it here i guess so:
> > /opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/client.py
> > or
> > /opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/dist-packages/client.py
> 
> I don't have either dist-packages or site-packages in any of my python folders

@lucilu1320  I found the folders but there's no client.py. Can you or anyone else share how to fix that?
