### ISSUE TITLE
Feature request:  tunnel Implementation

### ISSUE THREAD

**Issue by eduenriquez** [jofpin/trape#29]
What if you implement  a tunnel to expose your local trape to the world automatically ? 

https://localtunnel.github.io/www/
https://ngrok.com/ 

Tool of social phishing with ngrok already 
https://n0where.net/ultimate-phishing-tool-with-ngrok-integrated-socialfish

**Comment by jofpin** [comment]
Hey! Enjoy the new version 2.0 stable, brings many features included and correcting bugs. 

https://github.com/jofpin/trape

Share the World and Happy hacking!
