### ISSUE TITLE
sh: cls: command not found

### ISSUE THREAD

**Issue by rranjanjanacare** [jofpin/trape#31]
I am getting this following error while running the trape.py on MAC OS

> sh: cls: command not found
Currently there is no support for Windows.
	--------------------
	> Welcome to trape <
	--------------------
[*] Hello MacBook-Pro.local, I hope you enjoy my role
[x] You must run in mode root to be able to operate.

Any ideas, what could be wrong.

**Comment by jofpin** [comment]
Hey! Enjoy the new version 2.0 stable, brings many features included and correcting bugs. 

https://github.com/jofpin/trape

Share the World and Happy hacking!
