### ISSUE TITLE
el cliente le carga la pagina pero no se ve conectado

### ISSUE THREAD

**Issue by gearcapitan** [jofpin/trape#33]
![captura de pantalla 249](https://user-images.githubusercontent.com/13740942/36011415-9f92c496-0d1c-11e8-9bdb-9a8025f073f6.png)

 que procede?

**Comment by Blask0** [comment]
Me pasa lo mismo, lo solucionaste?

**Comment by gearcapitan** [comment]
nop

**Comment by Blask0** [comment]
lo hiciste teniendo una red de clase c?

**Comment by gearcapitan** [comment]
pues si normal, pero la verdad eso lo hice hace mucho y ya ni me acordaba de este post q levante :/

**Comment by jofpin** [comment]
Hey! Enjoy the new version 2.0 stable, brings many features included and correcting bugs. 

https://github.com/jofpin/trape

Share the World and Happy hacking!
