### ISSUE TITLE
Remotely Sending files

### ISSUE THREAD

**Issue by WinXprt** [jofpin/trape#34]
While sending files from our system to victim system it is showing as below
![image](https://user-images.githubusercontent.com/32786723/36094128-0b7c386a-1013-11e8-8890-1f772b32fe96.png)

![image](https://user-images.githubusercontent.com/32786723/36094138-16af1716-1013-11e8-841e-841883726311.png)

**Comment by WinXprt** [comment]
I have kept calc.exe file in the trape/static/files/ folder path.

**Comment by Slenderhack** [comment]
I have the same problem , i put the file in trape/static/file already but  it continues showing Not found

**Comment by JPYamamoto** [comment]
This could be happening because the browser is blocking pop-up windows. Could you confirm whether your browser is doing this?

**Comment by jofpin** [comment]
Hey! Enjoy the new version 2.0 stable, brings many features included and correcting bugs. 

https://github.com/jofpin/trape

Share the World and Happy hacking!
