### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by killercoderz4** [jofpin/trape#45]
Good day guys. i setup everything on my  ubuntu linux vps sever. and ran command pythone trape.py - u url -p port 443. now everything started smoothly . i login to control panel. now when i visit victim link on my pc, it doesn't capture anything. the log is empty.Thanks

**Comment by xlr80** [comment]
wont work over wlan try with ngrok

**Comment by jofpin** [comment]
Hey! Enjoy the new version 2.0 stable, brings many features included and correcting bugs. 

https://github.com/jofpin/trape

Share the World and Happy hacking!
