### ISSUE TITLE
link for targets doesn't work in mobile phones

### ISSUE THREAD

**Issue by ashu021** [jofpin/trape#46]
i installed the tool everything is perfect i tried on myself.when i opened the victim link in my pc it worked perfectly . But when i tried to open the same link in smartphone, it simply doesn't load the site ,i tried several times.i wanted to know that this tool works only on pc's because it's doesn't work in smartphones.

**Comment by jofpin** [comment]
Hey! Enjoy the new version 2.0 stable, brings many features included and correcting bugs. 

https://github.com/jofpin/trape

Share the World and Happy hacking!

**Comment by samberkni** [comment]
> 
> 
> i installed the tool everything is perfect i tried on myself.when i opened the victim link in my pc it worked perfectly . But when i tried to open the same link in smartphone, it simply doesn't load the site ,i tried several times.i wanted to know that this tool works only on pc's because it's doesn't work in smartphones.

does session recognition work for you
