### ISSUE TITLE
cannot track  redirect

### ISSUE THREAD

**Issue by asciiterminal** [jofpin/trape#50]
so i have set google as an attack perimeter and while i access the google link from there in the search bar when i type any website the error pops 
that do you want to leave or stay nothing else

**Comment by vepicurean** [comment]
I get the same behaviour with the target url web page.  The page doesn't render properly and those strange questions show if I try to close the browser window. I don't think Trape is working properly at this moment.

**Comment by jofpin** [comment]
Hey! Enjoy the new version 2.0 stable, brings many features included and correcting bugs. 

https://github.com/jofpin/trape

Share the World and Happy hacking!
