### ISSUE TITLE
Invalid requirement: '<<<<<<< HEAD'

### ISSUE THREAD

**Issue by xShuden** [jofpin/trape#69]
Getting this: https://ibb.co/SQG0zKd

When trying to run: pip3 install -r requirements.txt

on a first install. Used to work fine. Using Python 3.6.7

**Comment by aancw** [comment]
I think he is accidently paste that text when commit or doing git(or it was produced by git commit). Update your requirements.txt like this:
```
Flask
Flask-Login
Flask-Session
flask-socketio
flask_socketio
flask_cors
itsdangerous
Jinja2
MarkupSafe
python-engineio
python-socketio
six
Werkzeug
eventlet
requests
```
