### ISSUE TITLE
Error: nonnumeric port

### ISSUE THREAD

**Issue by pablojimpas** [jofpin/trape#76]
I'm trying to test this tool, I've install it and configure my tokens in the initial run, then when I try to use it with a example url I get this strange error.
![screenshot from 2018-11-26 15-23-32](https://user-images.githubusercontent.com/17835916/49017112-4cbb7500-f188-11e8-8190-955e9728266b.png)  

If I add the port in the url the error doesn't show up but it keeps asking me for the url...
![screenshot from 2018-11-26 15-24-38](https://user-images.githubusercontent.com/17835916/49017114-4d540b80-f188-11e8-8136-4dee630869a1.png)

**Comment by mrameezraja** [comment]
try changing port. i.e 8090.

**Comment by jofpin** [comment]
fixed https://github.com/jofpin/trape/commit/6aacd3c34a167185e48f37723a053b3fc2c35002
