### ISSUE TITLE
No sessions or location displayed

### ISSUE THREAD

**Issue by DJCHICKEN4** [jofpin/trape#93]
When I go into the control panel for trape it displays a pop up when I click on a name stating that the location of the user is not allowed also none of the sessions are displayed as active even when logged in I’m running this on a Kali Linux virtual machine.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by M2z** [comment]
Did you manage to solve somehow the issue of the active sessions and map?

**Comment by DJCHICKEN4** [comment]
>Did you manage to solve somehow the issue of the active sessions and map?

@M2z no but multiple questions already existed with the same issue so I closed this one.

**Comment by freeman68** [comment]
Hi, have you solved this issue? I am having the same problem..
